export const actionTypes = {
    DANG_NHAP: 'DANG_NHAP',
    DANG_KY: 'DANG_KY',
    LOAI_NGUOI_DUNG: 'LOAI_NGUOI_DUNG',
    LAY_DANH_SACH_NGUOI_DUNG: 'LAY_DANH_SACH_NGUOI_DUNG',
    CHINH_SUA_NGUOI_DUNG: 'CHINH_SUA_NGUOI_DUNG',
<<<<<<< HEAD
    CAP_NHAT_NGUOI_DUNG: 'CAP_NHAT_NGUOI_DUNG',
    TIM_KIEM_NGUOI_DUNG: 'TIM_KIEM_NGUOI_DUNG',
    THONG_TIN_TAI_KHOAN:'THONG_TIN_TAI_KHOAN'
=======
    CAP_NHAT_NGUOI_DUNG: 'CAP_NHAT_NGUOI_DUNG'
>>>>>>> master
}