export const actionTypes = {
    LAY_DANH_SACH_PHIM : 'LAY_DANH_SACH_PHIM',
    LAY_DANH_SACH_RAP : 'LAY_DANH_SACH_RAP',
    LAY_DANH_SACH_PHIM_THEO_RAP: 'LAY_DANH_SACH_PHIM_THEO_RAP',
    LAY_DANH_SACH_PHIM_THEO_TRANG : 'LAY_DANH_SACH_PHIM_THEO_TRANG'
}