export const actionTypes = {
    LAY_DANH_SACH_PHIM : 'LAY_DANH_SACH_PHIM',
    LAY_DANH_SACH_RAP : 'LAY_DANH_SACH_RAP',
    LAY_DANH_SACH_RAP_THEO_CUM_RAP: 'LAY_DANH_SACH_RAP_THEO_CUM_RAP',
    LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP: 'LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP',
    THEM_PHIM: 'THEM_PHIM',
    LAY_THONG_TIN_PHIM: 'LAY_THONG_TIN_PHIM'
}